model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: "os.environ/GEMINI_API_KEY"
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: "os.environ/GEMINI_API_KEY"
  - model_name: llama3
    litellm_params:
      model: ollama/llama3
      api_base: "http://ollama:11434"
  - model_name: mistral
    litellm_params:
      model: ollama/mistral
      api_base: "http://ollama:11434"
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: mxbai-embed-large
    litellm_params:
      model: ollama/mxbai-embed-large
      api_base: "http://ollama:11434"

general_settings:
  master_key: sk-1234
  allow_requests_on_db_unavailable: true
  database_connection_pool_limit: 10
  disable_error_logs: true
  disable_spend_logs: true

litellm_settings:
  cache: true
  cache_params:
    ttl: 600
    type: redis
    host: redis
    port: 6379
    namespace: litellm.caching
  json_logs: true
  request_timeout: 600
  set_verbose: false
