[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Exclude large data and cache directories
norecursedirs = data .venv __pycache__ .git outputs documentation docs

# Show extra summary info
addopts = -ra -q
